### ISSUE TITLE
PyPi package appears not to have the setup.py file.

### ISSUE THREAD

**Issue by BurritoBazooka** [nak/pywebkit3#3]
Thanks for doing this, but the [package on PIP](https://pypi.python.org/pypi/PyGGI/0.8.12) appears to be devoid of a setup.py file.

    ~ $ sudo pip install pyggi
    Downloading/unpacking pyggi
      Could not find any downloads that satisfy the requirement pyggi
    No distributions at all found for pyggi
    Storing complete log in /home/user/.pip/pip.log
    ~ $ sudo pip install PyGGI
    Downloading/unpacking PyGGI
      Could not find any downloads that satisfy the requirement PyGGI
    No distributions at all found for PyGGI
    Storing complete log in /home/user/.pip/pip.log

    ~/Downloads/PyGGI $ find | grep setup
    ~/Downloads/PyGGI $ 

    ~/Downloads/PyGGI $ sudo pip install ./
    Directory './' is not installable. File 'setup.py' not found.
    Storing complete log in /home/user/.pip/pip.log
    ~/Downloads/PyGGI $ sudo pip install ./pyggi/
    Directory './pyggi/' is not installable. File 'setup.py' not found.
    Storing complete log in /home/user/.pip/pip.log
    ~/Downloads/PyGGI $ sudo pip install ./pywebkit3/
    Directory './pywebkit3/' is not installable. File 'setup.py' not found.
    Storing complete log in /home/user/.pip/pip.log
    ~/Downloads/PyGGI $ sudo pip install ./EGG-INFO/
    Directory './EGG-INFO/' is not installable. File 'setup.py' not found.
    Storing complete log in /home/user/.pip/pip.log

Sure, it's on PIP, and as noted in the README that is one of the stated goals of this project, but there's no setup.py file that PIP can use, it seems.

(e.t.a. attempts at installing with PIP)

**Comment by nak** [comment]
I'm able to pip install this cleanly so I think this is resolved.
